version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  welcome: circleci/welcome-orb@0.4.1
  
workflows:
  welcome:
    jobs:
      - welcome/run
      - slack/notify-on-failure:
          only_for_branches: master
