name: Continuous Delivery
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: npm i && npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Tests
        run: npm i && npm t
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check For Security Issues
        run: npm audit
  deploy-production:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: npm i && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
  verify-production:
    runs-on: ubuntu-latest
    #needs: [deploy-production]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Smoke Test
        run: npm i && npm run smoke
