name: Continuous Delivery
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "!master"

jobs:
  # _________                __  .__
  # \_   ___ \  ____   _____/  |_|__| ____  __ __  ____  __ __  ______
  # /    \  \/ /  _ \ /    \   __\  |/    \|  |  \/  _ \|  |  \/  ___/
  # \     \___(  <_> )   |  \  | |  |   |  \  |  (  <_> )  |  /\___ \
  #  \______  /\____/|___|  /__| |__|___|  /____/ \____/|____//____  >
  #         \/            \/             \/                        \/
  # .___        __                              __  .__
  # |   | _____/  |_  ____   ________________ _/  |_|__| ____   ____
  # |   |/    \   __\/ __ \ / ___\_  __ \__  \\   __\  |/  _ \ /    \
  # |   |   |  \  | \  ___// /_/  >  | \// __ \|  | |  (  <_> )   |  \
  # |___|___|  /__|  \___  >___  /|__|  (____  /__| |__|\____/|___|  /
  #          \/          \/_____/            \/                    \/

  build: # Reduce human error by compiling on new code.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: npm i && npm run build

  test: # Reduce human error by running unit tests every time there's new code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Tests
        run: npm i && npm t

  audit: # Do you perform audits often? Probably not. Having it here makes it a daily thing.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check For Security Issues
        run: npm audit --audit-level=critical

  # _________                __  .__
  # \_   ___ \  ____   _____/  |_|__| ____  __ __  ____  __ __  ______
  # /    \  \/ /  _ \ /    \   __\  |/    \|  |  \/  _ \|  |  \/  ___/
  # \     \___(  <_> )   |  \  | |  |   |  \  |  (  <_> )  |  /\___ \
  #  \______  /\____/|___|  /__| |__|___|  /____/ \____/|____//____  >
  #         \/            \/             \/                        \/
  # ________                .__                                      __
  # \______ \   ____ ______ |  |   ____ ___.__. _____   ____   _____/  |_
  #  |    |  \_/ __ \\____ \|  |  /  _ <   |  |/     \_/ __ \ /    \   __\
  #  |    `   \  ___/|  |_> >  |_(  <_> )___  |  Y Y  \  ___/|   |  \  |
  # /_______  /\___  >   __/|____/\____// ____|__|_|  /\___  >___|  /__|
  #         \/     \/|__|               \/          \/     \/     \/

  deploy-production: # Reduce human error by deploying exactly the same way every time.
    runs-on: ubuntu-latest
    needs: [build, test, audit]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: npm i && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

  verify-production: # Automating a smoke test prevents friday deploys from turning into weekend death marches.
    runs-on: ubuntu-latest
    needs: [deploy-production]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Smoke Test
        run: export TEST_URL=https://codex.academy && npm i && npm run smoke
