name: Continuous Delivery
on: push

jobs:
  #   _________                __  .__
  # \_   ___ \  ____   _____/  |_|__| ____  __ __  ____  __ __  ______
  # /    \  \/ /  _ \ /    \   __\  |/    \|  |  \/  _ \|  |  \/  ___/
  # \     \___(  <_> )   |  \  | |  |   |  \  |  (  <_> )  |  /\___ \
  #  \______  /\____/|___|  /__| |__|___|  /____/ \____/|____//____  >
  #         \/            \/             \/                        \/
  # .___        __                              __  .__
  # |   | _____/  |_  ____   ________________ _/  |_|__| ____   ____
  # |   |/    \   __\/ __ \ / ___\_  __ \__  \\   __\  |/  _ \ /    \
  # |   |   |  \  | \  ___// /_/  >  | \// __ \|  | |  (  <_> )   |  \
  # |___|___|  /__|  \___  >___  /|__|  (____  /__| |__|\____/|___|  /
  #          \/          \/_____/            \/                    \/
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm i
      - name: Lint the code
        npm: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm i
      - name: Run Unit Tests
        run: npm t

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check for security issue
        run: npm audit --audit-level=critical
