name: CICD
on: push
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v1
      - 
        name: "Setup Node"
        node-version: 13.x
        uses: actions/setup-node@v1
        with: ~
      - 
        name: "Install Dependencies"
        run: "npm i"
      - 
        name: "Build the code"
        run: "npm run build"
name: CICD
test: 
  needs: 
    - build
  runs-on: ubuntu-latest
  steps: 
    - 
      name: Checkout
      uses: actions/checkout@v1
    - 
      name: "Setup Node"
      uses: actions/setup-node@v1
      with: 
        node-version: 13.x
    - 
      name: "Install Dependencies"
      run: "npm i"
    - 
      name: "Test the code"
      run: "npm run test"
true: push
