name: Continuous Delivery
on: [push]

jobs:
  #  _____             _   _
  # /  __ \           | | (_)
  # | /  \/ ___  _ __ | |_ _ _ __  _   _  ___  _   _ ___
  # | |    / _ \| '_ \| __| | '_ \| | | |/ _ \| | | / __|
  # | \__/\ (_) | | | | |_| | | | | |_| | (_) | |_| \__ \
  #  \____/\___/|_| |_|\__|_|_| |_|\__,_|\___/ \__,_|___/
  #  _____      _                       _   _
  # |_   _|    | |                     | | (_)
  #   | | _ __ | |_ ___  __ _ _ __ __ _| |_ _  ___  _ __
  #   | || '_ \| __/ _ \/ _` | '__/ _` | __| |/ _ \| '_ \
  #  _| || | | | ||  __/ (_| | | | (_| | |_| | (_) | | | |
  #  \___/_| |_|\__\___|\__, |_|  \__,_|\__|_|\___/|_| |_|
  #                      __/ |
  #                     |___/

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.8.0

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build
      
      - name: Store Artifact 
        uses: actions/upload-artifact@v2
        with:
          name: website-dist
          path: dist                                                                  |___/
